
name: SPECTER
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  specter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install xray
        run: |
          curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/download/v1.8.6/Xray-windows-64.zip
          powershell -Command "Expand-Archive -Force xray.zip ."
          del xray.zip
      - name: Install dependencies
        run: pip install requests
      - name: Run
        run: python specter.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
